<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'ç³»ç»Ÿåˆ†ç±»',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => 'ç³»ç»Ÿä¿ç•™åˆ†ç±»',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '12',
    'cat_name' => 'èµ„è®¯ä¸­å¿ƒ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '0',
    'has_children' => '3',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '13',
    'cat_name' => 'èµ°è¿›å½¼å²¸',
    'cat_type' => '1',
    'keywords' => 'èµ°è¿›å½¼å²¸ï¼Œå½¼å²¸é£Ÿå“ï¼Œç¼¤çº·å½¼å²¸ï¼Œè¿›å£é£Ÿå“',
    'cat_desc' => 'èµ°è¿›å½¼å²¸ï¼Œå½¼å²¸é£Ÿå“ï¼Œç¼¤çº·å½¼å²¸ï¼Œè¿›å£é£Ÿå“',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '3Gèµ„è®¯',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  4 => 
  array (
    'cat_id' => '11',
    'cat_name' => 'æ‰‹æœºä¿ƒé”€',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'ç½‘åº—ä¿¡æ¯',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => 'ç½‘åº—ä¿¡æ¯åˆ†ç±»',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  6 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'ç½‘åº—å¸®åŠ©åˆ†ç±»',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => 'ç½‘åº—å¸®åŠ©åˆ†ç±»',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  7 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'æ–°æ‰‹ä¸Šè·¯ ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  8 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'æ‰‹æœºå¸¸è¯† ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => 'æ‰‹æœºå¸¸è¯† ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  9 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'é…é€ä¸Žæ”¯ä»˜ ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => 'é…é€ä¸Žæ”¯ä»˜ ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  10 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'æœåŠ¡ä¿è¯ ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  11 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'è”ç³»æˆ‘ä»¬ ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => 'è”ç³»æˆ‘ä»¬ ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  12 => 
  array (
    'cat_id' => '10',
    'cat_name' => 'ä¼šå‘˜ä¸­å¿ƒ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  13 => 
  array (
    'cat_id' => '15',
    'cat_name' => 'å…¬å¸åŠ¨æ€',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  14 => 
  array (
    'cat_id' => '16',
    'cat_name' => 'è¡Œä¸šèµ„è®¯',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  15 => 
  array (
    'cat_id' => '17',
    'cat_name' => 'åª’ä½“å…³æ³¨',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
);
?>