<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'é¥®æ–™ç³»åˆ—',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => 'é¥®æ–™ç³»åˆ—',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'åŒæ¨¡æ‰‹æœº',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 1,
    'id' => '5',
    'name' => 'åŒæ¨¡æ‰‹æœº',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'CDMAæ‰‹æœº',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => 'CDMAæ‰‹æœº',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'GSMæ‰‹æœº',
    'measure_unit' => 'å°',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '3',
    'name' => 'GSMæ‰‹æœº',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '3Gæ‰‹æœº',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '4',
    'name' => '3Gæ‰‹æœº',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => 'ä¼‘é—²ç³»åˆ—',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => 'ä¼‘é—²ç³»åˆ—',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => 'è”é€šæ‰‹æœºå……å€¼å¡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '15',
    'name' => 'è”é€šæ‰‹æœºå……å€¼å¡',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => 'å°çµé€š/å›ºè¯å……å€¼å¡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => 'å°çµé€š/å›ºè¯å……å€¼å¡',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => 'ç§»åŠ¨æ‰‹æœºå……å€¼å¡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '14',
    'name' => 'ç§»åŠ¨æ‰‹æœºå……å€¼å¡',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'æ‰‹æœºé…ä»¶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => 'æ‰‹æœºé…ä»¶',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'è€³æœº',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '8',
    'name' => 'è€³æœº',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'ç”µæ± ',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => 'ç”µæ± ',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => 'è¯»å¡å™¨å’Œå†…å­˜å¡',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '11',
    'name' => 'è¯»å¡å™¨å’Œå†…å­˜å¡',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'å……ç”µå™¨',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => 'å……ç”µå™¨',
  ),
);
?>